version: '3.7'

services:
  server:
    build: .
    volumes:
      - ./:/go/src/shogi-board-server/
    ports:
      - '8081:8081'
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '10'
    container_name: 'shogi-board-server'
