# Logger Config
# https://github.com/uber-go/zap

level: 'debug'
sampling:
  initial: 100
  thereafter: 100
encoding: 'console' # or json
encoderConfig:
  timeKey: 'time'
  levelKey: 'level'
  nameKey: 'logger'
  callerKey: 'caller'
  messageKey: 'msg'
  stacktraceKey: 'stacktrace'
  levelEncoder: ''
  timeEncoder: 'iso8601' # be empty for timestamp
  durationEncoder: ''
  callerEncoder: ''
outputPaths:
  - 'stdout'
errorOutputPaths:
  - 'stderr'
